### ISSUE TITLE
Can you bring geocode_catastral back?

### ISSUE THREAD

**Issue by Rakias1314** [rOpenSpain/spanish#1]
Can you please bring the geocode_catastral function back? I need it for a project I am working

**Comment by verajosemanuel** [comment]
Hi @Rakias1314 

I'm working on it. CRAN is getting a little "picky" and some NOTES are keeping the function back from being released.

In the meantime, you can use the package `ESmisc` as  `spanish` is based on it:

```
devtools::install_github("verajosemanuel/ESmisc") 
```

Thanks
