### ISSUE TITLE
spanish - rostemplate project

### ISSUE THREAD

**Issue by dieghernan** [rOpenSpain/spanish#2]
https://github.com/orgs/rOpenSpain/projects

Dear developers,

I have created a fork including the deploy of your package on your master/docs folder using the rostemplate (see Slack channel and https://ropenspain.github.io/rostemplate/). See a live preview of your `pkgdown` site here:
https://dieghernan.github.io/spanish/

An additional GitHub Action `check-standard.yaml` has been included. That action would check your package (AS CRAN) on several platforms on every push, pull request and every first day of the month. The goal is to provide CI on your package.

Note that this action could be redudant with your _travis current configuration, but you can still keep both without interferences between them.

## Actions on your package:

- Check locally and rebuild documentation (upgrade Roxygen version)

- Implementation of github-actions and related .gitgnore and .Rbuildignore.

- Modifications in logo and README: Logo has been rebuilt using `hexSticker` and README badges are relocated, ready to use with `pkgdown`. Favicons created using `pkgdown::build_favicon()`.
Old Logo: ![Old logo](https://raw.githubusercontent.com/dieghernan/spanish/master/tools/readme/logo-bk.png)
New Logo: ![New logo](https://raw.githubusercontent.com/dieghernan/spanish/master/tools/readme/logo.png)

Code for logo: https://github.com/dieghernan/spanish/blob/master/tools/readme/logo.R

**Please feel free to reject any changes you don't agree with**

## Next steps
 You should receive a Pull Request with these modifications.

After your review and in case you consider merging, consider to deploy Github Pages on your settings (master/docs folder).

Once it is done, I would appreciate if you move this issue to the Deployed tab on the [Project panel](https://github.com/orgs/rOpenSpain/projects) (see also Projects tab on this website).

---
LOG

- @dieghernan reviewing
-  @verajosemanuel owner

Fork: https://github.com/dieghernan/spanish
Live preview: https://dieghernan.github.io/spanish/

TODO: Open issue and pull request. Some changes on README and a new logo has been provided. Final deploy up to repo owner

**Comment by verajosemanuel** [comment]
Great! Quiero decir, grandioso!
Había un nuevo diseño completo del sitio (colores, logotipos...) que no recuerdo quién tenía en su disco duro. Quizás sea el momento de retomarlo. Por mi parte solo debería aceptar el PR ¿Cierto?

**Comment by dieghernan** [comment]
Así es. Te pediría que todavía no lo aceptes, voy a cambiar el logo con tu propuesta en Slack. Si consigues recuperar el que comentas dímelo y podemos hacer un PR más adelante

**Comment by dieghernan** [comment]
> Great! Quiero decir, grandioso!
> Había un nuevo diseño completo del sitio (colores, logotipos...) que no recuerdo quién tenía en su disco duro. Quizás sea el momento de retomarlo. Por mi parte solo debería aceptar el PR ¿Cierto?

He modificado el logo:

Old Logo: ![Old logo](https://raw.githubusercontent.com/dieghernan/spanish/master/tools/readme/logo-bk.png)
New Logo: ![New logo](https://raw.githubusercontent.com/dieghernan/spanish/master/tools/readme/logo.png)

Code for logo: https://github.com/dieghernan/spanish/blob/master/tools/readme/logo.R

**Comment by dieghernan** [comment]
Por mi parte ya se podría aceptar #3 , cualquier tema adicional házmelo saber. No he eliminado travis de tu repo, entiendo que quizá prefieras hacerlo tú mismo.

**Comment by verajosemanuel** [comment]
Aceptado. Todo OK. Gracias
