### ISSUE TITLE
to_number("y") gives out zero

### ISSUE THREAD

**Issue by Azbeltk** [rOpenSpain/spanish#5]
I'm trying to turn all numbers written as words on a sentence into numeric characters (if you want it).

Then I noticed that "cero" isn't recognized as the number zero, but "y" is taken as zero instead. 

I can bypass this on my code with an if statement but I wanted to let you know.

**Comment by verajosemanuel** [comment]
Hi Azbeltk
Could you give me an example? I can not imagine an integer number with the word “cero”.  Remember this function does no process decimals.
regards

**Comment by Azbeltk** [comment]
Sorry, I understand this is out of the scope intended.

I understand this function does not process decimals and I was thinking as integers in the math sense (which includes zero) instead of programming integers. Then I thought it was weird that to_number("y") = 0, since the word "y" is not zero. Let me give a bit of context as to why this issue came up.

I'm using it on some 4th grade math class transcriptions so sometimes the teaches says the number zero and I'm trying to convert every number on the transcription into the corresponding number character.  

So what I did was take each sentence from the transcription, split it using spaces and then to each word it removed the special character, the numbers and the remaining sting is passed to the to_number function in a tryCatch, so when it's not a number, it gives and error so I leave the word as is, and when it's not an error, then I replace the converted string on the original phrase. This is when I noticed that the string "y" and the string "" are returned as "cero" by to_number. 

I'm adding the functions I used.

```
library(spanish)
library(stringr)

numb <- function(word){
  tryCatch(
    {
      # try to turn the word into number and return the string for it
      as.character(to_number(word))
    },
    error = function(cond){
      # when it's not a number, keep the word as is
      word
    },
    warning = function(cond){
      # in case of a warning
    },
    finally = {
      # in case another message is needed
    }
  )  
}

split_phrase <- function(phrase){
  # split into words using spaces
  words = unlist(str_split(phrase," "))
  # run on every word
  for(i in 1:length(words)){
    w = words[i]
    # remove symbols
    no_punct = gsub("[[:punct:]]", "", w)
    # remove numbers
    no_numbe = gsub("[0-9]","",no_punct)
    # check if it's "y"
    if(tolower(no_numbe)=="y"){
      # keep the string "y"
      to_numbe = no_numbe
    } else if(tolower(no_numbe)=="cero"){
      # turn "cero" into 0
      to_numbe = "0"
    } else if(no_numbe==""){
      # keep the empty string
      to_numbe = ""
    } else{
      # turn word into number (if possible)
      to_numbe = numb(no_numbe)
    }
    # replace converted word into the original
    words[i] = gsub(no_numbe,to_numbe,w)
  }
  # collapse back again with spaces
  return(paste(words,collapse = " "))
}
```

**Comment by verajosemanuel** [comment]
oh, i see.
Good approach. Thanks for the tip. 
I will close this issue as “out of scope”
Thanks
